### PR TITLE
Picks up common 3.6.6, bump to 2.2.3, Remove the broker check for MSA FRT saving function.

### PR DESCRIPTION
**Pull request by rpdome**
Also fix bugs where MSA FRT is blocked from being saved when broker is enabled. (Broker doesn't support SSO for MSA yet).

### CODE REVIEW

**Review by AdamBJohnsonx — APPROVED** [review]
I assume the tests pass locally.

**Review by iamgusain — APPROVED** [review]
Updated the PR title to say common 3.6.6  (was 3.3.6)

**Comment by rpdome** [comment]
force pushed to trigger the newly added required checks.

**Review by shoatman — APPROVED** [review]

**Comment by p3dr0rv** [comment]
@rpdome  You will need to remove the MSAL Test App, Msal PR Validation, msal CredScan required check, 
those will no run because you don't have the YAML in this branch.

**Pull request merged**
