### PR TITLE
Changes related to pending intent removal

### PR DESCRIPTION
**Pull request by kreedula**

### CODE REVIEW

**Comment by kreedula** [comment]
@heidijinxujia I haven't removed `BrowserTabActivity` as a part of this PR. Looks we do validate a lot of things related to that. I am not sure why is that required and also per docs we ask developers to include that. I see no purpose , Can you take a look into this and let us know if this can safely be removed ?

**Comment by iambmelt** [comment]
> @heidijinxujia I haven't removed `BrowserTabActivity` as a part of this PR. Looks we do validate a lot of things related to that. I am not sure why is that required and also per docs we ask developers to include that. I see no purpose , Can you take a look into this and let us know if this can safely be removed ?

There would be docs/readme changes associated with this; let's include the README changes in this PR if we decide to remove

**Comment by kreedula** [comment]
Created an issue : https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/595 to remove `BrowserTabActivity` in another PR since @heidijinxujia is OOF. Merging this PR for now to get the release unblocked

**Comment by heidijinxujia** [comment]
BrowserTabActivity is still needed for Browser flow. Let me check your PR in details. Thank you.

**Comment by heidijinxujia** [comment]
BTW, have you tested with browser flow? I am wondering how did it redirect back from an external browser without BrowserTabActivity...

**Pull request merged**
