### PR TITLE
Add ability to provide common version using project property

### PR DESCRIPTION
**Pull request by iamgusain**
Add ability to provide common version using project property
Related PR on broker: https://github.com/AzureAD/ad-accounts-for-android/pull/1788

### CODE REVIEW

**Comment by shahzaibj** [comment]
So even during releases we have to now supply version from command line?

**Comment by iamgusain** [comment]
> So even during releases we have to now supply version from command line?

For release branches we edit version "0.0.+" to the latest RC or final release version just to make it clear, same way as we do today
Command line is to mainly add support daily/dev or private builds

**Comment by AdamBJohnsonx** [comment]
> > So even during releases we have to now supply version from command line?
> 
> For release branches we edit version "0.0.+" to the latest RC or final release version just to make it clear, same way as we do today Command line is to mainly add support daily/dev or private builds

Would be a nice thing to be able to automate that portion of the build.  I suppose we could use a GitHub action to edit the file in-place and check it in?

**Review by AdamBJohnsonx — APPROVED** [review]
Sure?  It's editing the property in once place instead of two...

**Review by shahzaibj — APPROVED** [review]

**Pull request merged**
