### PR TITLE
Kill HTTP layer adapters. make changes to accommodate common

### PR DESCRIPTION
**Pull request by rpdome**
See: https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/1396

### CODE REVIEW

**Comment by iambmelt** [comment]
@rpdome Can you include a changelog update in this PR calling out that this is breaking?

**Comment by rpdome** [comment]
> @rpdome Can you include a changelog update in this PR calling out that this is breaking?
> 
> Edit - this PR doesn't appear to be breaking at this level - we should still have a changelog update calling out this change :)

In a sense, this PR is an equivalent of "update common". The actual work isn't in this layer.

I could definitely add it to change log though (didn't add it _now_ because I thought it would be very 'noisy', since there will be more PR on the way that looks like this).

**Comment by rpdome** [comment]
NVM, just saw your edit. I suspect that it might have something to do with shadows. Let me take a look.

**Review by iambmelt — APPROVED** [review]
I don't see any issue with these changes, though it appears there may a failure or cancellation of some test: perhaps this is expected
image

**Comment by rpdome** [comment]
> I don't see any issue with these changes, though it appears there may a failure or cancellation of some test: perhaps this is expected
> image

Issue with robolectric's flushScheduler (not sure why it just showed up).
Switching to the LEGACY mode fixed it. There's a PBI for fixing this in the PAUSED mode https://dev.azure.com/IdentityDivision/Engineering/_workitems/edit/1377749

**Review by iambmelt — APPROVED** [review]

**Review by shahzaibj — APPROVED** [review]

**Review by AdamBJohnsonx — APPROVED** [review]

**Comment by rpdome** [comment]
rebased dev.

**Pull request merged**
