### PR TITLE
Fix MSAL issue #779

### PR DESCRIPTION
**Pull request by shahzaibj**
In this PR I've fixed MSAL issue #779 
See #779 

To fix this issue, I check if callback is null before we call any onSuccess or onError methods on it and then we throw an IllegalStateException if the callback is null

### CODE REVIEW

**Comment by shahzaibj** [comment]
@iambmelt Thanks! Constant error string has been added.

**Comment by iambmelt** [comment]
@shahzaibj :shipit:

**Comment by shahzaibj** [comment]
> LGTM, just to make sure, these are only methods where we return the result to user right?

@kreedula 
Inside PublicClientApplication.java yes, however, there are other methods in MultipleAccountPublicClientApplication.java where we use callback to pass the result to the user such as the `getAccount` method. The `getAccount` method or other such methods inside MultipleAccountPCA class do not have any validate Non Null logic at this time. These methods don't accept that many parameters but I think it might still be good to validate non null on these. What do you say?

**Comment by kreedula** [comment]
Thanks @shahzaibj . Lets get this in and take in a fresh change for the methods mentioned

**Pull request merged**
