### PR TITLE
Update Logger imports to use new API in Common

### PR DESCRIPTION
**Pull request by iambmelt**
Picks up changes in:
https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/1279

### CODE REVIEW

**Comment by iambmelt** [comment]
Marking as draft, found more usages....

**Comment by iambmelt** [comment]
CI failing due to MSAL updates needed per:
https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/1299

@AdamBJohnsonx FYI looks like your PR here didn't merge:
https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/1352

**Comment by AdamBJohnsonx** [comment]
Merged it

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by iambmelt** [comment]
This PR ready for 👀

**Review by AdamBJohnsonx — APPROVED** [review]
This one is boring.

**Pull request merged**
