### PR TITLE
Update common submodule - 1/29/2021

### PR DESCRIPTION
**Pull request by shahzaibj**

### CODE REVIEW

**Review by AdamBJohnsonx — APPROVED** [review]
Have to wonder how hard it would be to move to consuming this as an aar just like we have MSAL-cpp do it.

**Review by iambmelt — APPROVED** [review]

**Comment by shahzaibj** [comment]
> Have to wonder how hard it would be to move to consuming this as an aar just like we have MSAL-cpp do it.

The issues are mostly around automation where some things are passed in as cmd parameters to common's BuildConfig...once we change that then it would be possible. I can create a work item to track this and we can pick it up in a future sprint. After that I think we can add a variant to MSAL to just consume `0.0.+` version of common

**Comment by AdamBJohnsonx** [comment]
> > Have to wonder how hard it would be to move to consuming this as an aar just like we have MSAL-cpp do it.
> 
> The issues are mostly around automation where some things are passed in as cmd parameters to common's BuildConfig...once we change that then it would be possible. I can create a work item to track this and we can pick it up in a future sprint. After that I think we can add a variant to MSAL to just consume `0.0.+` version of common

We're chipping away at it.  Some of the Broker things are going to be moot post one of your changes.  Definitely create an item to enumerate and track the rest of them.  Why aren't they an issue for OneAuth/MSAL-cpp?

**Comment by shahzaibj** [comment]
> > > Have to wonder how hard it would be to move to consuming this as an aar just like we have MSAL-cpp do it.
> > 
> > 
> > The issues are mostly around automation where some things are passed in as cmd parameters to common's BuildConfig...once we change that then it would be possible. I can create a work item to track this and we can pick it up in a future sprint. After that I think we can add a variant to MSAL to just consume `0.0.+` version of common
> 
> We're chipping away at it. Some of the Broker things are going to be moot post one of your changes. Definitely create an item to enumerate and track the rest of them. Why aren't they an issue for OneAuth/MSAL-cpp?

I think they are an issue for OneAuth...at least there was an email some time ago where this exact issue was brought up by OneAuth

**Comment by AdamBJohnsonx** [comment]
> > > > Have to wonder how hard it would be to move to consuming this as an aar just like we have MSAL-cpp do it.
> > > 
> > > 
> > > The issues are mostly around automation where some things are passed in as cmd parameters to common's BuildConfig...once we change that then it would be possible. I can create a work item to track this and we can pick it up in a future sprint. After that I think we can add a variant to MSAL to just consume `0.0.+` version of common
> > 
> > 
> > We're chipping away at it. Some of the Broker things are going to be moot post one of your changes. Definitely create an item to enumerate and track the rest of them. Why aren't they an issue for OneAuth/MSAL-cpp?
> 
> I think they are an issue for OneAuth...at least there was an email some time ago where this exact issue was brought up by OneAuth

I know the "valid broker" bit was a problem.  Would be curious to know what else there was.  Doesn't have to be here, in the work item.

**Comment by shahzaibj** [comment]
> > > > > Have to wonder how hard it would be to move to consuming this as an aar just like we have MSAL-cpp do it.
> > > > 
> > > > 
> > > > The issues are mostly around automation where some things are passed in as cmd parameters to common's BuildConfig...once we change that then it would be possible. I can create a work item to track this and we can pick it up in a future sprint. After that I think we can add a variant to MSAL to just consume `0.0.+` version of common
> > > 
> > > 
> > > We're chipping away at it. Some of the Broker things are going to be moot post one of your changes. Definitely create an item to enumerate and track the rest of them. Why aren't they an issue for OneAuth/MSAL-cpp?
> > 
> > 
> > I think they are an issue for OneAuth...at least there was an email some time ago where this exact issue was brought up by OneAuth
> 
> I know the "valid broker" bit was a problem. Would be curious to know what else there was. Doesn't have to be here, in the work item.

@AdamBJohnsonx Created work item and added the details here: https://dev.azure.com/IdentityDivision/Engineering/_workitems/edit/1277730

**Comment by shahzaibj** [comment]
Tests are currently failing due to known issue with HttpClient shadow (and that is already being worked on)

**Pull request merged**
