### PR TITLE
Fix the removeAccount for local cache when broker installed

### PR DESCRIPTION
**Pull request by heidijinxujia**
**Problem**
#653
The getAcquireTokenController only generator one controller out of local controller and broker controller. For getAccount, getAccounts and removeAccount call, essentially, we should load the account both locally and from broker as well.

**Solution**
Call MSALControllerFactory.getAcquireTokenSilentControllers() to construct the account command. Thus, when the broker eligible, it will trigger both local controller and broker controller. If not, it will only trigger the local controller. 

In this PR, I also update our msal test app to utilize the lab's test account. This change was blocked by the redirect uri registration.

**E2E**
Tested with both CP and Authenticator (ad-accounts RC26)
1. Install MSAL test app, login with cloud account A.
2. Click "GET USERS", it will show the info for account A.
3. Install CP or Authenticator
4. Open MSAL test app and login with a MAM account B, finish the registration and you should see the token returned.
5. Click "GET USERS", it will show the info for both Account A and Account B
6. Type in the loginhint for Account A, and click "REMOVE ACCOUNT", it shows "the account is removed successfully"
7. Click "GET USERS" it will show the account B only
8. Type in the loginhint for Account B, and click "REMOVE ACCOUNT", it shows "the account is removed successfully"
9. Click "REMOVE USER", it shows an empty list.

### CODE REVIEW

**Comment by heidijinxujia** [comment]
@heidijinxujia This debug.keystore is from [our repo](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/testapps/testapp/debug/debug.keystore).

**Comment by iambmelt** [comment]
Scenario where both controllers _should_ be hit:
- AppA signs in to MSAL without broker using account `user@contoso.com`
- AppB signs in to a MAM protected app using `user@contoso.com`, broker is installed
- AppA calls `removeAccount()` on `user@contoso.com`

**Comment by kreedula** [comment]
Thanks @iambmelt , here is the code where we always set the result returned from last controller, which is Broker controller https://github.com/AzureAD/microsoft-authentication-library-common-for-android/blob/dev/common/src/main/java/com/microsoft/identity/common/internal/controllers/RemoveAccountCommand.java#L67

**Comment by heidijinxujia** [comment]
@iambmelt @kreedula The removeAccount will only return true when the account is removed successfully from local (and broker if the broker is eligible to use) or no account is found in local cache (and broker cache if broker is eligible). It will not return false, instead, it will throw the exception with error code and detailed reasons if anything goes wrong during the removing.

**Pull request merged**
