### PR TITLE
Breaking MSAL with Broker tests down into more packages

### PR DESCRIPTION
**Pull request by fadidurah**
PR that relocates some of the MSAL with Broker Ui automation test cases into packages that better describe which area of the test plan they belong to. The newly created packages are:
- api
- endshift
- joined
- nonjoined
- sovereigncloud

### CODE REVIEW

**Comment by shahzaibj** [comment]
1561151 should probably move into the `joined` folder.
850457 should probably move into the `non-joined` folder.

**Comment by shahzaibj** [comment]
Let's rename `api` to `brokerapi`
Let's rename `endshift` to `flw`

**Comment by fadidurah** [comment]
> 1561151 should probably move into the `joined` folder. 850457 should probably move into the `non-joined` folder.

seems like 497069 can also go into `nonjoined`, and 1561185 can go in `joined`?

**Comment by shahzaibj** [comment]
> > 1561151 should probably move into the `joined` folder. 850457 should probably move into the `non-joined` folder.
> 
> seems like 497069 can also go into `nonjoined`, and 1561185 can go in `joined`?

Yes!

**Comment by fadidurah** [comment]
Closing this PR since these changes will be merged with the fadi/repair PRs

**Pull request closed without merging**
